---
spring:
  resources.static-locations: "file:./app"
cds:
  odatav4.endpoint.path: "/api"

---
spring:
  profiles: cloud

---
spring:
  profiles: sqlite-predeployed
  datasource:
    url: "jdbc:sqlite:/home/user/projects/bookshop-java/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never # to be filled with `npm run deploy`

---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
