---
spring:
  resources.static-locations: "file:./app"
cds:
  odatav4.endpoint.path: "/api"

---
spring:
  profiles: cloud

---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:/home/user/projects/bookshop-java/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never # to be filled with `npm run deploy`
  resources.static-locations: "file:/home/user/projects/bookshop-java/app" # for fast UI-dev turnarounds

---
spring:
  profiles: test
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
