---
spring:
  resources:
    static-locations: "file:./app"
cds:
  security:
    mock:
      users:
      - name: admin
        password: admin
        roles:
        - admin
      - name: user
        password: user
---
spring:
  profiles: cloud
---
spring:
  profiles: sqlite
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:file::memory:?cache=shared"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: always
